#if defined _language_dialogs_inc
	#endinput
#endif
#define _language_dialogs_inc


new const language_dialog[][][] =
{
	{//EN
		{
			//DG_ADD_ANIMATION,
			"Add animation\n\t \n"
		},
		{
			//DG_APPLY_ANIM_REMOVE_FROM_LIST,
			"Apply animation\n\
			Remove animation from the list"
		},
		{
			//DG_ADD_ANIM_ENTER_TITLE_INDEX,
			"To add an animation, enter the name and Index separated by a comma\n\
			Note: Do not use commas/dots between words"
		},
		{
			//DG_ENTER_HEX_SLCT_REMOVE_COLOR,
			"Enter HEX color cod\n\
			Choose a color from the list\n\t\n\
			Remove color from the object"
		},
		{
			//DG_ENTER_HEX_COLOR,
			"Enter the color in HEX format, for example, FF0000\n\n\
			To find a color, you can use the website: htmlcolorcodes.com\nNote: Some colors may display incorrectly on objects"
		},
		{
			//DG_APPLY_RMV_COLOR_FROM_LIST,
			"Apply color\n\
			Remove color from the list"
		},
		{
			//DG_CONFIRM_DELETE_PROCESS,
			"Are you sure you want to delete this process?"
		},
		{
			//DG_CONFIRM_DUPLICATE_PROCESS,
			"Are you sure you want to duplicate this process?"
		},
		{
			//DG_ENTER_COMMENT,
			"Enter a comment\n\
			If no comment is needed, leave the field empty and press »"
		},
		{
			//DG_DATA_EXPORT_SUCCESS,
			"Data successfully exported. Path: scriptfiles/project/export/project_name"
		},
		{
			//DG_NUM_NAME_OBJECT_COMMENT,
			"#\tTitle\tObject\tComment\n"
		},
		{
			//DG_SET_MODEL_ADD_SELECT_OBJECT,
			"Set object model\n\t\n\
			Add object to the list\n\
			Select object from the list"
		},
		{
			//DG_ENTER_ATTACHMENT_OBJ_MODEL,
			"Enter object model for attachment"
		},
		{
			//DG_SET_OBJECT_REMOVE_FROM_LIST,
			"Set object\n\
			Remove object from the list"
		},
		{
			//DG_ENTER_OBJECT_MODEL_TO_ADD,
			"To add an object to the list, enter the object model\n\
			To find the model ID, you can use the website: dev.prineside.com"
		},
		{
			//DG_ENTER_SKIN_ID_TO_SET,
			"To set the skin, enter the ID"
		},
		{
			//DG_ENTER_PROJECT_NAME,
			"Enter a name for the project"
		},
		{
			//DG_LOAD_PRJCT_REMOVE_FROM_LIST,
			"Load project\n\
			Remove project from the list"
		},
		{
			//DG_CREATE_LOAD_CLS_HELP_PROJECT,
			"Create project\n\
			Load project\n\
			Close project\n\t\n\
			Help"
		},
		{
			//DG_ADD_COLOR_HEX_CODE,
			"Add HEX color code\n\t\n"
		},
		{
			//DG__MAIN_MENU_HELP,
			"Manage \n\
			- Left-click opens a dialogue with created processes\n\
			- Right-click opens a dialogue for selecting multiple processes simultaneously\n\
			Export - Export project\n\
			New - Create a new process\n\
			Delete - Delete process\n\
			Duplicate - Duplicate process\n\
			Bone - Modify bone for the current process\n\
			Symmetry - Create a symmetrical mirrored object from the current one\n\
			Objects\n\
			- Left-click opens a dialogue for choosing to set an object or selecting from the list\n\
			- Right-click opens a menu for selecting objects from the list\n\
			Edit - Edit object\n\
			Color\n\
			- Left-click opens a dialogue for choosing to set a color or selecting from the list\n\
			- Right-click opens a menu for selecting colors from the list\n\
			Camera Move - Enable/disable camera rotation with an active panel\n\
			Skin - Set skin\n\
			Prev Skin & Next Skin\n\
			- Left-click enables quick skin change\n\
			- Right-click enables quick skin change and automatic project export\n\
			Animation - Set animation\n\
			Clear Anim - Clear animation\n\n\
			/headmove - Enable/disable character head rotation\n\
			/setweather - Set weather\n\
			/settime - Set time"
		},
		{
			//DG_ADD_COLOR_HEX_IN_LIST,
			"To add color, enter the color in HEX format, for example, FF0000\n\
			To find the color, you can use the website: htmlcolorcodes.com\n\n\
			Note: Some colors may appear incorrectly on objects."
		},
		{
			//DG_CONFIRM_MULT_DELETE_PROCESS,
			"Do you really want to delete all selected processes?"
		},
		{
			//DG_MULTIOBJECT_LIST_MANAGE,
			"Clear\n\t\n"
		}
	},
	{//RU
		{
			//DG_ADD_ANIMATION,
			"Добавить анимацию\n\t \n"
		},
		{
			//DG_APPLY_ANIM_REMOVE_FROM_LIST,
			"Применить анимацию\n\
			Удалить анимацию из списка"
		},
		{
			//DG_ADD_ANIM_ENTER_TITLE_INDEX,
			"Чтобы добавить анимацию введите название и Index, через запятую.\n\
			Примечание: Не используйте запятые/точки между словами"
		},
		{
			//DG_ENTER_HEX_SLCT_REMOVE_COLOR,
			"Установить HEX-код цвета\n\
			Выберите цвет из списка\n\t\n\
			Удалить цвет с объекта"
		},
		{
			//DG_ENTER_HEX_COLOR,
			"Введите цвет в формате HEX, например, FF0000.\n\n\
			Чтобы узнать цвет, вы можете воспользоваться сайтом: htmlcolorcodes.com\n\
			Примечание: Некоторые цвета могут отображаться некорректно на объектах"
		},
		{
			//DG_APPLY_RMV_COLOR_FROM_LIST,
			"Применить цвет\n\
			Удалить цвет из списка"
		},
		{
			//DG_CONFIRM_DELETE_PROCESS,
			"Вы уверены, что хотите удалить данный процесс?"
		},
		{
			//DG_CONFIRM_DUPLICATE_PROCESS,
			"Вы уверены, что хотите продублировать данный процесс?"
		},
		{
			//DG_ENTER_COMMENT,
			"Введите комментарий\n\
			Если комментарий не требуется, оставьте поле пустым и нажмите »"
		},
		{
			//DG_DATA_EXPORT_SUCCESS,
			"Данные успешно экспортированы. Путь: scriptfiles/project/export/название_проекта"
		},
		{
			//DG_NUM_NAME_OBJECT_COMMENT,
			"#\tНазвание\tОбъект\tКомментарий\n"
		},
		{
			//DG_SET_MODEL_ADD_SELECT_OBJECT,
			"Установить модель объекта\n\t\n\
			Добавить объект в список\nВыбрать объект из списка"
		},
		{
			//DG_ENTER_ATTACHMENT_OBJ_MODEL,
			"Введите модель объекта для аттача"
		},
		{
			//DG_SET_OBJECT_REMOVE_FROM_LIST,
			"Установить объект\nУдалить объект из списка"
		},
		{
			//DG_ENTER_OBJECT_MODEL_TO_ADD,
			"Чтобы добавить объект в список, введите модель объекта.\n\
			Чтобы узнать ID модели, вы можете воспользоваться сайтом: dev.prineside.com"
		},
		{
			//DG_ENTER_SKIN_ID_TO_SET,
			"Чтобы установить скин, введите ID"
		},
		{
			//DG_ENTER_PROJECT_NAME,
			"Введите название для проекта"
		},
		{
			//DG_LOAD_PRJCT_REMOVE_FROM_LIST,
			"Загрузить проект\nУдалить проект из списка"
		},
		{
			//DG_CREATE_LOAD_CLS_HELP_PROJECT,
			"Создать проект\n\
			Загрузить проект\n\
			Закрыть проект\n\t\n\
			Помощь"
		},
		{
			//DG_ADD_COLOR_HEX_CODE,
			"Добавить HEX-код цвета\n\t\n"
		},
		{
			//DG__MAIN_MENU_HELP,
			"Manage \n\
			- Нажатие левой кнопкой мыши, открывает диалог с созданными процессами\n\
			- Нажатие правой кнопкой мыши, открывает диалог для выбора несколько процессов одновременно\n\
			Export - Экспортировать проект\n\
			New - Создать новый процесс\n\
			Delete - Удалить процесс\n\
			Dublicate - Продублировать процесс\n\
			Bone - Изменить кость для текущего процесса\n\
			Symmetry - Создать симметрический отзеркаленый объект от текущего\n\
			Objects\n\
			- Нажатие левой кнопкой мыши, открывает диалог с выбором установить объект или выбрать из списка\n\
			- Нажатие правой кнопкой мыши, открывает меню выбора объектов из списка\n\
			Edit - Редактирование объекта\n\
			Color\n\
			- Нажатие левой кнопкой мыши, открывает диалог с выбором установить цвет или выбрать из списка\n\
			- Нажатие правой кнопкой мыши, открывает меню выбора цвета из списка\n\
			Camera Move - Включить/отключить вращение камеры при активной панели\n\
			Skin - Установить skin\n\
			Prev Skin & Next Skin\n\
			- Нажатие левой кнопкой мыши, быстрая смена скина\n\
			- Нажатие правой кнопкой мыши, быстрая смена скина и автоматический экспорт проекта\n\
			Animation - Установить анимацию\n\
			Clear Anim - Очистить анимацию\n\n\
			/headmove - Включить/отключить вращение головы у персонажа\n\
			/setweather - Установить погоду\n\
			/settime - Установить время"
		},
		{
			//DG_ADD_COLOR_HEX_IN_LIST,
			"Чтобы добавить цвет, введите цвет в формате HEX, например, FF0000\n\
			Чтобы узнать цвет, вы можете воспользоваться сайтом: htmlcolorcodes.com\n\n\
			Примечание: Некоторые цвета могут отображаться некорректно на объектах."
		},
		{
			//DG_CONFIRM_MULT_DELETE_PROCESS,
			"Вы действительно хотите удалить все выбранные процессы?"
		},
		{
			//DG_MULTIOBJECT_LIST_MANAGE,
			"Очистить\n\t\n"
		}
	},
	{//UA
		{
			//DG_ADD_ANIMATION,
			"Додати анiмацiю\n\\t\n"
		},
		{
			//DG_APPLY_ANIM_REMOVE_FROM_LIST,
			"Застосувати анiмацiю\n\
			Видалити анiмацiю зi списку"
		},
		{
			//DG_ADD_ANIM_ENTER_TITLE_INDEX,
			"Щоб додати анiмацiю введiть назву та iндекс, роздiленi комою.\n\
			Примiтка: Не використовуйте коми/точки мiж словами"
		},
		{
			//DG_ENTER_HEX_SLCT_REMOVE_COLOR,
			"Застосувати HEX-код кольору\n\
			Виберiть колiр зi списку\n\
			\t\n\
			Видалити колiр з об'єкта"
		},
		{
			//DG_ENTER_HEX_COLOR,
			"Введiть колiр у форматi HEX, наприклад, FF0000\n\n\
			Щоб знайти колiр, можете скористатися веб-сайтом: htmlcolorcodes.com\n\
			Примiтка: Деякi кольори можуть вiдображатися некоректно на об'єктах"
		},
		{
			//DG_APPLY_RMV_COLOR_FROM_LIST,
			"Застосувати колiр\nВидалити колiр зi списку"
		},
		{
			//DG_CONFIRM_DELETE_PROCESS,
			"Ви впевненi, що хочете видалити цей процес?"
		},
		{
			//DG_CONFIRM_DUPLICATE_PROCESS,
			"Ви впевненi, що хочете продублювати цей процес?"
		},
		{
			//DG_ENTER_COMMENT,
			"Введiть коментар\n\
			Якщо коментар не потрiбен, залиште поле порожнiм i натиснiть »"
		},
		{
			//DG_DATA_EXPORT_SUCCESS,
			"Данi успiшно експортованi. Шлях: scriptfiles/project/export/iм'я_проекту"
		},
		{
			//DG_NUM_NAME_OBJECT_COMMENT,
			"#\tНазва\tОб'єкт\tКоментар\n"
		},
		{
			//DG_SET_MODEL_ADD_SELECT_OBJECT,
			"Встановити модель об'єкта\n\t\n\
			Додати об'єкт до списку\n\
			Вибрати об'єкт iз списку"
		},
		{
			//DG_ENTER_ATTACHMENT_OBJ_MODEL,
			"Введiть модель об'єкта для прикрiплення"
		},
		{
			//DG_SET_OBJECT_REMOVE_FROM_LIST,
			"Встановити об'єкт\n\
			Видалити об'єкт iз списку"
		},
		{
			//DG_ENTER_OBJECT_MODEL_TO_ADD,
			"Щоб додати об'єкт до списку, введiть модель об'єкта\n\
			Щоб дiзнатися ID моделi, ви можете скористатися веб-сайтом: dev.prineside.com"
		},
		{
			//DG_ENTER_SKIN_ID_TO_SET,
			"Щоб встановити скiн, введiть ID"
		},
		{
			//DG_ENTER_PROJECT_NAME,
			"Введiть назву для проекту"
		},
		{
			//DG_LOAD_PRJCT_REMOVE_FROM_LIST,
			"Завантажити проект\n\
			Видалити проект iз списку"
		},
		{
			//DG_CREATE_LOAD_CLS_HELP_PROJECT,
			"Створити проект\n\
			Завантажити проект\n\
			Закрити проект\n\t\n\
			Довiдка"
		},
		{
			//DG_ADD_COLOR_HEX_CODE,
			"Додати HEX-код кольору\n\t\n"
		},
		{
			//DG_MAIN_MENU_HELP,
			"Manage \n\
			- Натискання лiвої кнопки мишi вiдкриває дiалог зi створеними процесами\n\
			- Натискання правої кнопки мишi вiдкриває дiалог для вибору декiлькох процесiв одночасно\n\
			Export - Експорт проекту\n\
			New - Створити новий процес\n\
			Delete - Видалити процес\n\
			Duplicate - Створити копiю процесу\n\
			Bone - Змiнити кiстку для поточного процесу\n\
			Symmetry - Створити симетричний вiдзеркалений об'єкт вiд поточного\n\
			Objects\n\
			- Натискання лiвої кнопки мишi вiдкриває дiалог для вибору установки об'єкта або вибору зi списку\n\
			- Натискання правої кнопки мишi вiдкриває меню вибору об'єктiв iз списку\n\
			Edit - Редагування об'єкта\n\
			Color\n\
			- Натискання лiвої кнопки мишi вiдкриває дiалог для вибору установки кольору або вибору зi списку\n\
			- Натискання правої кнопки мишi вiдкриває меню вибору кольорiв iз списку\n\
			Camera Move - Увiмкнути/вимкнути обертання камери при активнiй панелi\n\
			Skin - Встановити шкiру\n\
			Prev Skin & Next Skin\n\
			- Натискання лiвої кнопки мишi для швидкої змiни скина\n\
			- Натискання правої кнопки мишi для швидкої змiни скина та автоматичного експорту проекту\n\
			Animation - Встановити анiмацiю\n\
			Clear Anim - Очистити анiмацiю\n\n\
			/headmove - Увiмкнути/вимкнути обертання голови у персонажа\n\
			/setweather - Встановити погоду\n\
			/settime - Встановити час"
		},
		{
			//DG_ADD_COLOR_HEX_IN_LIST,
			"Щоб додати колiр, введiть колiр у форматi HEX, наприклад, FF0000\n\
			Щоб дiзнатися колiр, ви можете скористатися веб-сайтом: htmlcolorcodes.com\n\n\
			Примiтка: Деякi кольори можуть вiдображатися некоректно на об'єктах."
		},
		{
			//DG_CONFIRM_MULT_DELETE_PROCESS,
			"Ви дiйсно бажаєте видалити всi обранi процеси?"
		},
		{
			//DG_MULTIOBJECT_LIST_MANAGE,
			"Очистити\n\t\n"
		}
	},
	{//BY
		{
			//DG_ADD_ANIMATION,
			"Дадаць анiмацыю\n\t \n"
		},
		{
			//DG_APPLY_ANIM_REMOVE_FROM_LIST,
			"Прымянiць анiмацыю\n\
			Выдалiць анiмацыю з спiску"
		},
		{
			//DG_ADD_ANIM_ENTER_TITLE_INDEX,
			"Каб дадаць анiмацыю, увядзiце назву i iндэкс, падзеленыя коскi\n\
			Заўвага: Не выкарыстоўвайце коскi/кропкi памiж словамi"
		},
		{
			//DG_ENTER_HEX_SLCT_REMOVE_COLOR,
			"Увядзiце HEX колер cod\n\
			Выбярыце колер з спiску\n\
			\t\n\
			Удалiць колер з праэкту"
		},
		{
			//DG_ENTER_HEX_COLOR,
			"Увядзiце колер у HEX фармаце, на прыклад, FF0000\n\n\
			Каб знайсцi, вы можаце iспользваць сайт: htmlcolorcodes.com\n\
			Увага: Некалькi колераў могуць быць нявернымi на аб`ектах"
		},
		{
			//DG_APPLY_RMV_COLOR_FROM_LIST,
			"Прымянiць колер\n\
			Выдалiць колер з спiску"
		},
		{
			//DG_CONFIRM_DELETE_PROCESS,
			"Хочаце выдалiць гэты працэс?"
		},
		{
			//DG_CONFIRM_DUPLICATE_PROCESS,
			"Хочаце паўтарыць гэты працэс?"
		},
		{
			//DG_ENTER_COMMENT,
			"Увядзiце заўвагу\n\
			Калi заўвага не патрабуецца, пакiньце поле пустым i нацiснiце»"
		},
		{
			//DG_DATA_EXPORT_SUCCESS,
			"Дадзеныя паспяхова экспартаваныя. Шлях: scriptfiles/project/export/назва праэкту"
		},
		{
			//DG_NUM_NAME_OBJECT_COMMENT,
			"#\tНазва\tАб`ект\tЗаўвага\n"
		},
		{
			//DG_SET_MODEL_ADD_SELECT_OBJECT,
			"Стварыць мадэль да аб'екту\n\t\n\
			Стварыць абъект да спiску\n\
			Выбярыце аб`ект з спiску"
		},
		{
			//DG_ENTER_ATTACHMENT_OBJ_MODEL,
			"Увядзiце мадэль да аб'екту для ўкладання"
		},
		{
			//DG_SET_OBJECT_REMOVE_FROM_LIST,
			"Паставiць аб`ект\nВыдзялiць аб`ект з спiску"
		},
		{
			//DG_ENTER_OBJECT_MODEL_TO_ADD,
			"Каб add an object to the list, enter the object model\n\
			To find the model ID, you can use the website: dev.prineside.com"
		},
		{
			//DG_ENTER_SKIN_ID_TO_SET,
			"Каб set the skin, enter the ID"
		},
		{
			//DG_ENTER_PROJECT_NAME,
			"Увядзiце назву да праэкта"
		},
		{
			//DG_LOAD_PRJCT_REMOVE_FROM_LIST,
			"Загрузiць праэкт\nВыцiснуць праэкт з списку"
		},
		{
			//DG_CREATE_LOAD_CLS_HELP_PROJECT,
			"Стварыць праэкт\n\
			Загрузiць праэкт\n\
			Закрыць праэкт\n\t\n\
			Дапамога"
		},
		{
			//DG_ADD_COLOR_HEX_CODE,
			"Дадаць HEX каляровай код\n\t\n"
		},
		{
			//DG_MAIN_MENU_HELP,
			"Manage \n\
			- Нацiсканне левай кнопкай мышы адчыняе дыялог з створанымi працэсамi\n\
			- Нацiсканне правай кнопкай мышы адчыняе дыялог для выбару некалькiх працэсаў адначасова\n\
			Export - Экспартаваць праект\n\
			New - Стварыць новы працэс\n\
			Delete - Выдалiць працэс\n\
			Dublicate - Прадубляваць працэс\n\
			Bone - Змянiць косьць для бягучага працэсу\n\
			Symmetry - Стварыць сiметрычны адзеркалены аб'ект ад бягучага\n\
			Objects\n\
			- Нацiсканне левай кнопкай мышы адчыняе дыялог з выбарам устанавiць аб'ект цi выбраць з спiсу\n\
			- Нацiсканне правай кнопкай мышы адчыняе мэню выбару аб'ектаў з спiсу\n\
			Edit - Рэдагаванне аб'екта\n\
			Color\n\
			- Нацiсканне левай кнопкай мышы адчыняе дыялог з выбарам устанавiць колер цi выбраць з спiсу\n\
			- Нацiсканне правай кнопкай мышы адчыняе мэню выбару колеру з спiсу\n\
			Camera Move - Уключыць/адключыць варачэнне камеры пры актыўнай панэлi\n\
			Skin - Устанавiць скiн\n\
			Prev Skin & Next Skin\n\
			- Нацiсканне левай кнопкай мышы, хуткая змена скiна\n\
			- Нацiсканне правай кнопкай мышы, хуткая змена скiна i аўтаматычны экспарт праекта\n\
			Animation - Устанавiць анiмацыю\n\
			Clear Anim - Ачысцiць анiмацыю\n\n\
			/headmove - Уключыць/адключыць варачэнне галавы ў персанажа\n\
			/setweather - Устанавiць надвор'е\n\
			/settime - Устанавiць час"
		},
		{
			//DG_ADD_COLOR_HEX_IN_LIST,
			"Каб дадаць колер, увядзiце колер у фармаце HEX, напрыклад, FF0000\n\
			Каб даведацца пра колер, вы можаце выкарыстоўваць вэб-сайт: htmlcolorcodes.com\n\n\
			Увага: Некаторыя колеры могуць адлюстроўвацца некарэктна на аб'ектах"
		},
		{
			//DG_CONFIRM_MULT_DELETE_PROCESS,
			"Вы сапраўды жадаеце выдалiць усе выбраныя працэсы?"
		},
		{
			//DG_MULTIOBJECT_LIST_MANAGE,
			"Ачысцiць\n\t\n"
		}
	}
};