#if defined _language_messages_inc
	#endinput
#endif
#define _language_messages_inc


new const language_message[][][] =
{
	{//EN
		{
			//MSG_START_ROBOT_PRESS_MAIN_END
			"To start the robot, press the {38A584}Y {FFFFFF}key"
		},
		{
			//MSG_ANIM_APPLIED_TO_CHARACTER
			"Animation applied to the character in"
		},
		{
			//MSG_ANIM_REMOVED_SUCCESS
			"The animation has been successfully removed"
		},
		{
			//MSG_ANIM_EXISTS_WITH_INDEX
			"Animation with this index already exists"
		},
		{
			//MSG_PROCESS_START_PRESS_NEW
			"For the start, create a process, press {38A584}NEW"
		},
		{
			//MSG_START_SELECT_OBJ_PRESS_OBJ
			"For the start, select an object, press {38A584}Objects"
		},
		{
			//MSG_COLOR_HEX_REMOVED_SUCCESS
			"HEX color code successfully removed from the object"
		},
		{
			//MSG_INVALID_COLOR_HEX_CODE
			"invalid HEX color code"
		},
		{
			//MSG_COLOR_HEX_APPLIED_SUCCESS
			"HEX color code successfully applied to the object"
		},
		{
			//MSG_COLOR_REMOVED_SUCCESS
			"Color successfully removed"
		},
		{
			//MSG_COLOR_EXISTS_WITH_HEX_CODE
			"Color with this HEX code already exists"
		},
		{
			//MSG_NEW_COLOR_ADDED_TO_LIST
			"New color successfully added to the list"
		},
		{
			//MSG_NO_CREATED_PROCESS_FOUND
			"The created process is not present"
		},
		{
			//MSG_MAX_COMMENT_LENGTH_IS_CHARS
			"Maximum comment length is 31 characters"
		},
		{
			//MSG_OBJECT_DUPLICATED_SUCCESS
			"Object successfully duplicated"
		},
		{
			//MSG_FREE_LOOK_HOLD_SPRINT_KEY
			"To freely look around, hold down the sprint key ({38A584}Shift{FFFFFF}/{38A584}Space{FFFFFF})"
		},
		{
			//MSG_SAVE_PRESS_ICON_CNL_USE_ESC
			"To save changes, click on the {38A584}Save icon{FFFFFF} to cancel, use the {38A584}ESC {FFFFFF}key"
		},
		{
			//MSG_NOT_SAVED_EDITING_CANCELLED
			"Changes were not saved as editing was canceled"
		},
		{
			//MSG_CHANGES_SAVED_AFTER_EDIT
			"Changes after editing have been successfully saved"
		},
		{
			//MSG_LIST_ATTACHED_OBJECTS_EMPTY
			"The list attached objects is empty"
		},
		{
			//MSG_NO_AVAILABLE_ATTACH_SLOTS
			"No available slots for attachment"
		},
		{
			//MSG_TO_SET_OBJECT_PRESS_OBJECTS
			"To install the object, press {38A584}Objects"
		},
		{
			//MSG_TO_MNG_ATTAC_PRESS_MANAGE
			"To manage attached objects, press {38A584}Manage"
		},
		{
			//MSG_PRTCT_FRM_ACCIDENTAL_CLICK
			"Protection against accidental clicks"
		},
		{
			//MSG_INVALID_OBJECT_MODEL
			"invalid object model"
		},
		{
			//MSG_PRESS_TO_EDIT_START_EDITING
			"To start editing the attachment, press {38A584}Edit"
		},
		{
			//MSG_OBJECT_REMOVED_SUCCESS
			"Object successfully deleted"
		},
		{
			//MSG_OBJECT_MODEL_EXISTS_WITH_ID
			"An object model with this iD already exists"
		},
		{
			//MSG_OBJECT_MODEL_ADDED_SUCCESS
			"Object model successfully added to the list"
		},
		{
			//MSG_SPECIFY_SKIN_ID_IN_RANGE
			"Specify the skin iD from 1 to 311"
		},
		{
			//MSG_SKIN_SET_SUCCESS
			"Skin successfully set"
		},
		{
			//MSG_CLOSE_CURRENT_PROJECT_FIRST
			"To start, close the current project"
		},
		{
			//MSG_MAX_PROJECT_LENGTH_IS_CHARS
			"Maximum project name is %d characters"
		},
		{
			//MSG_ONLY_LATIN_LETTERS_DIGITS
			"Only Latin letters and numbers without spaces are allowed for input"
		},
		{
			//MSG_PROJECT_WITH_NAME_EXISTS
			"A project with this name already exists"
		},
		{
			//MSG_PRJCT_NAME_SUCCESS_CREATED
			"Project successfully created"
		},
		{
			//MSG_FREE_LK_MODE_ACTIV_PRS_ESC
			"To activate free-look mode, press the {38A584}ESC {FFFFFF}key"
		},
		{
			//MSG_CURSOR_ACTIVATION_PRESS_N
			"To activate the cursor, press the {38A584}N {FFFFFF}key"
		},
		{
			//MSG_PROCESS_SRT_SLCT_OPTION_NEW
			"To start the process, choose the option {38A584}NEW"
		},
		{
			//MSG_PROJECTS_LIST_EMPTY
			"The list of projects is empty"
		},
		{
			//MSG_PRJCT_FILE_NO_FOUND_WH_NAME
			"Project file with the specified name not found"
		},
		{
			//MSG_PROJECT_LOADED_SUCCESS
			"Project successfully loaded"
		},
		{
			//MSG_PRJCT_RMOVD_FRM_LT_SUCCESS
			"Project successfully removed from the list"
		},
		{
			//MSG_NO_ACTIVE_PROJECT_FOUND
			"You don't have an active project"
		},
		{
			//MSG_CURRENT_PRJCT_CLSD_SUCCESS
			"Current project successfully closed"
		},
		{
			//MSG_SMTRY_NOT_FOUND_FREE_SLOT
			"To create symmetry for the object, free up one slot"
		},
		{
			//MSG_DUBLICT_NOT_FOUND_FREE_SLOT
			"There is no available slot for a duplicate; please remove one of the existing processes."
		},
		{
			//MSG_CHANGE_BONE
			"The new bone has been successfully implanted."
		},
		{
			//MSG_MULTIOBJ_INVALID_MODELID
			"This process does not have a specified object."
		},
		{
			//MSG_NO_AVAILABLE_MULTIPLE_OBJ
			"Not available during multiple selected processes simultaneously."
		}
	},
	{//RU
		{
			//MSG_START_ROBOT_PRESS_MAIN_END
			"Для начала роботы нажмите клавишу {38A584}Y"
		},
		{
			//MSG_ANIM_APPLIED_TO_CHARACTER
			"Анимация применена к персонажу"
		},
		{
			//MSG_ANIM_REMOVED_SUCCESS
			"Анимация успешно удалена"
		},
		{
			//MSG_ANIM_EXISTS_WITH_INDEX
			"Анимация с таким индексом уже существует"
		},
		{
			//MSG_PROCESS_START_PRESS_NEW
			"Для начала создайте процесс, нажмите {38A584}NEW"
		},
		{
			//MSG_START_SELECT_OBJ_PRESS_OBJ
			"Для начала выберите объект, нажмите {38A584}Objects"
		},
		{
			//MSG_COLOR_HEX_REMOVED_SUCCESS
			"HEX-код цвета успешно удален с объекта"
		},
		{
			//MSG_INVALID_COLOR_HEX_CODE
			"Некорректный HEX-код цвета"
		},
		{
			//MSG_COLOR_HEX_APPLIED_SUCCESS
			"HEX-код цвета успешно применен к объекту"
		},
		{
			//MSG_COLOR_REMOVED_SUCCESS
			"Цвет успешно удален"
		},
		{
			//MSG_COLOR_EXISTS_WITH_HEX_CODE
			"Цвет с таким hex кодом уже существует"
		},
		{
			//MSG_NEW_COLOR_ADDED_TO_LIST
			"Новый цвет успешно добавлен в список"
		},
		{
			//MSG_NO_CREATED_PROCESS_FOUND
			"Созданный процесс отсутствует"
		},
		{
			//MSG_MAX_COMMENT_LENGTH_IS_CHARS
			"Максимальная длина комментария - 31 символ"
		},
		{
			//MSG_OBJECT_DUPLICATED_SUCCESS
			"Объект успешно продублирован"
		},
		{
			//MSG_FREE_LOOK_HOLD_SPRINT_KEY
			"Для свободного обзора удерживайте клавишу бега ({38A584}Shift{FFFFFF}/{38A584}Space{FFFFFF})"
		},
		{
			//MSG_SAVE_PRESS_ICON_CNL_USE_ESC
			"Чтобы сохранить изменения, нажмите на иконку {38A584}Сохранить{FFFFFF}, для отмены используйте клавишу {38A584}ESC"
		},
		{
			//MSG_NOT_SAVED_EDITING_CANCELLED
			"Изменения не были сохранены, так как редактирование было отменено"
		},
		{
			//MSG_CHANGES_SAVED_AFTER_EDIT
			"Изменения после редактирования успешно сохранены"
		},
		{
			//MSG_LIST_ATTACHED_OBJECTS_EMPTY
			"Список прикрепленных объектов пуст"
		},
		{
			//MSG_NO_AVAILABLE_ATTACH_SLOTS
			"Нет доступных слотов для аттача"
		},
		{
			//MSG_TO_SET_OBJECT_PRESS_OBJECTS
			"Чтобы установить объект, нажмите {38A584}Objects"
		},
		{
			//MSG_TO_MNG_ATTAC_PRESS_MANAGE
			"Для управления прикрепленными объектами нажмите {38A584}Manage"
		},
		{
			//MSG_PRTCT_FRM_ACCIDENTAL_CLICK
			"Защита от случайного клика"
		},
		{
			//MSG_INVALID_OBJECT_MODEL
			"Модель объекта недопустима"
		},
		{
			//MSG_PRESS_TO_EDIT_START_EDITING
			"Для начала редактирования нажмите {38A584}Edit"
		},
		{
			//MSG_OBJECT_REMOVED_SUCCESS
			"Объект успешно удален"
		},
		{
			//MSG_OBJECT_MODEL_EXISTS_WITH_ID
			"Модель объекта с таким iD уже существует"
		},
		{
			//MSG_OBJECT_MODEL_ADDED_SUCCESS
			"Модель объекта успешно добавлена в список"
		},
		{
			//MSG_SPECIFY_SKIN_ID_IN_RANGE
			"Укажите iD скина от 1 до 311"
		},
		{
			//MSG_SKIN_SET_SUCCESS
			"Скин успешно установлен"
		},
		{
			//MSG_CLOSE_CURRENT_PROJECT_FIRST
			"Для начала закройте текущий проект"
		},
		{
			//MSG_MAX_PROJECT_LENGTH_IS_CHARS
			"Максимальная назва проекта - %d символ"
		},
		{
			//MSG_ONLY_LATIN_LETTERS_DIGITS
			"Для ввода разрешены только латинские буквы и цифры без пробелов"
		},
		{
			//MSG_PROJECT_WITH_NAME_EXISTS
			"Проект с таким названием уже существует"
		},
		{
			//MSG_PRJCT_NAME_SUCCESS_CREATED
			"Проект успешно создан"
		},
		{
			//MSG_FREE_LK_MODE_ACTIV_PRS_ESC
			"Для активации режима свободного просмотра, нажмите клавишу {38A584}ESC"
		},
		{
			//MSG_CURSOR_ACTIVATION_PRESS_N
			"Для активации курсора, нажмите клавишу {38A584}N"
		},
		{
			//MSG_PROCESS_SRT_SLCT_OPTION_NEW
			"Для начала процесса, выберите опцию {38A584}NEW"
		},
		{
			//MSG_PROJECTS_LIST_EMPTY
			"Список проектов пуст"
		},
		{
			//MSG_PRJCT_FILE_NO_FOUND_WH_NAME
			"Файл проекта с указанным названием не найден"
		},
		{
			//MSG_PROJECT_LOADED_SUCCESS
			"Проект успешно загружен"
		},
		{
			//MSG_PRJCT_RMOVD_FRM_LT_SUCCESS
			"Проект успешно удален из списка"
		},
		{
			//MSG_NO_ACTIVE_PROJECT_FOUND
			"У вас нет активного проекта"
		},
		{
			//MSG_CURRENT_PRJCT_CLSD_SUCCESS
			"Текущий проект успешно закрыт"
		},
		{
			//MSG_SMTRY_NOT_FOUND_FREE_SLOT
			"Чтобы сделать симметрию объекта, освободите один слот"
		},
		{
			//MSG_DUBLICT_NOT_FOUND_FREE_SLOT
			"Нет свободного слота для дубликата, удалите один имеющийся процесс."
		},
		{
			//MSG_CHANGE_BONE
			"Новая кость успешно установлена."
		},
		{
			//MSG_MULTIOBJ_INVALID_MODELID
			"У этого процесса не установлен объект."
		},
		{
			//MSG_NO_AVAILABLE_MULTIPLE_OBJ
			"Не доступно во время нескольких выбранных процессов одновременно."
		}
	},
	{//UA
		{
			//MSG_START_ROBOT_PRESS_MAIN_END
			"Для початку роботи натиснiть клавiшу {38A584}Y"
		},
		{
			//MSG_ANIM_APPLIED_TO_CHARACTER
			"Анiмацiя застосована до персонажу"
		},
		{
			//MSG_ANIM_REMOVED_SUCCESS
			"Анiмацiю успiшно видалено."
		},
		{
			//MSG_ANIM_EXISTS_WITH_INDEX
			"Анiмацiя з таким iндексом вже додана"
		},
		{
			//MSG_PROCESS_START_PRESS_NEW
			"Для початку створiть процес, натиснiть {38A584}NEW"
		},
		{
			//MSG_START_SELECT_OBJ_PRESS_OBJ
			"Для початку виберiть об'єкт, натиснiть {38A584}Objects"
		},
		{
			//MSG_COLOR_HEX_REMOVED_SUCCESS
			"HEX-код кольору успiшно видалено з об'єкта"
		},
		{
			//MSG_INVALID_COLOR_HEX_CODE
			"Некоректний HEX-код кольору"
		},
		{
			//MSG_COLOR_HEX_APPLIED_SUCCESS
			"HEX-код кольору успiшно застосований до об'єкта"
		},
		{
			//MSG_COLOR_REMOVED_SUCCESS
			"Колiр успiшно видалено"
		},
		{
			//MSG_COLOR_EXISTS_WITH_HEX_CODE
			"Колiр з таким HEX-кодом вже додано"
		},
		{
			//MSG_NEW_COLOR_ADDED_TO_LIST
			"Новий колiр успiшно доданий до списку"
		},
		{
			//MSG_NO_CREATED_PROCESS_FOUND
			"Створений процес вiдсутнiй"
		},
		{
			//MSG_MAX_COMMENT_LENGTH_IS_CHARS
			"Максимальна довжина коментаря - 31 символiв"
		},
		{
			//MSG_OBJECT_DUPLICATED_SUCCESS
			"Предмет успiшно продубльовано"
		},
		{
			//MSG_FREE_LOOK_HOLD_SPRINT_KEY
			"Для вiльного перегляду тримайте клавiшу бiгу ({38A584}Shift{FFFFFF}/{38A584}Space{FFFFFF})"
		},
		{
			//MSG_SAVE_PRESS_ICON_CNL_USE_ESC
			"Для збереження змiн натиснiть на iконку {38A584}Зберегти{FFFFFF} для скасування використовуйте клавiшу ESC"
		},
		{
			//MSG_NOT_SAVED_EDITING_CANCELLED
			"Змiни не були збереженi, оскiльки редагування було скасовано"
		},
		{
			//MSG_CHANGES_SAVED_AFTER_EDIT
			"Змiни пiсля редагування успiшно збереженi"
		},
		{
			//MSG_LIST_ATTACHED_OBJECTS_EMPTY
			"Список прикрiплених об'єктів порожнiй"
		},
		{
			//MSG_NO_AVAILABLE_ATTACH_SLOTS
			"Немає доступних слотiв для прикрiплення"
		},
		{
			//MSG_TO_SET_OBJECT_PRESS_OBJECTS
			"Щоб встановити об'єкт, натиснiть {38A584}Objects"
		},
		{
			//MSG_TO_MNG_ATTAC_PRESS_MANAGE
			"Для управлiння прикрiпленими об'єктами натиснiть {38A584}Manage"
		},
		{
			//MSG_PRTCT_FRM_ACCIDENTAL_CLICK
			"Захист вiд випадкового клiка"
		},
		{
			//MSG_INVALID_OBJECT_MODEL
			"Неприпустима модель об'єкта"
		},
		{
			//MSG_PRESS_TO_EDIT_START_EDITING
			"Для початку редагування натиснiть Edit"
		},
		{
			//MSG_OBJECT_REMOVED_SUCCESS
			"Предмет успiшно видалено"
		},
		{
			//MSG_OBJECT_MODEL_EXISTS_WITH_ID
			"Модель об'єкта з таким iD вже додана"
		},
		{
			//MSG_OBJECT_MODEL_ADDED_SUCCESS
			"Модель об'єкта успiшно додана до списку"
		},
		{
			//MSG_SPECIFY_SKIN_ID_IN_RANGE
			"Вкажiть iD скина вiд 1 до 311"
		},
		{
			//MSG_SKIN_SET_SUCCESS
			"Скин успiшно встановлено"
		},
		{
			//MSG_CLOSE_CURRENT_PROJECT_FIRST
			"Для початку закрийте поточний проект"
		},
		{
			//MSG_MAX_PROJECT_LENGTH_IS_CHARS
			"Максимальна назва проекту - %d символiв"
		},
		{
			//MSG_ONLY_LATIN_LETTERS_DIGITS
			"Для введення дозволенi тiльки латинськi лiтери i цифри без вiдступiв"
		},
		{
			//MSG_PROJECT_WITH_NAME_EXISTS
			"Проект з такою назвою вже доданий"
		},
		{
			//MSG_PRJCT_NAME_SUCCESS_CREATED
			"Проект успiшно створено"
		},
		{
			//MSG_FREE_LK_MODE_ACTIV_PRS_ESC
			"Для активацiї режиму вiльного перегляду, натиснiть клавiшу {38A584}ESC"
		},
		{
			//MSG_CURSOR_ACTIVATION_PRESS_N
			"Для активацiї курсора, натиснiть клавiшу {38A584}N"
		},
		{
			//MSG_PROCESS_SRT_SLCT_OPTION_NEW
			"Для початку процесу виберiть опцiю {38A584}NEW"
		},
		{
			//MSG_PROJECTS_LIST_EMPTY
			"Список проектiв вiдсутнiй"
		},
		{
			//MSG_PRJCT_FILE_NO_FOUND_WH_NAME
			"Файл проекту з вказаною назвою не знайдено"
		},
		{
			//MSG_PROJECT_LOADED_SUCCESS
			"Проект успiшно завантажено"
		},
		{
			//MSG_PRJCT_RMOVD_FRM_LT_SUCCESS
			"Проект успiшно видалено зi списку"
		},
		{
			//MSG_NO_ACTIVE_PROJECT_FOUND
			"У вас вiдсутнiй активний проект"
		},
		{
			//MSG_CURRENT_PRJCT_CLSD_SUCCESS
			"Поточний проект успiшно закрито"
		},
		{
			//MSG_SMTRY_NOT_FOUND_FREE_SLOT
			"Щоб здійснити симетрію об'єкта, звiльнiть один слот"
		},
		{
			//MSG_DUBLICT_NOT_FOUND_FREE_SLOT
			"Немає вільного слоту для дубліката, видаліть існуючий процес."
		},
		{
			//MSG_CHANGE_BONE
			"Нова кістка успішно встановлена."
		},
		{
			//MSG_MULTIOBJ_INVALID_MODELID
			"У цьому процесі не встановлено об'єкт."
		},
		{
			//MSG_NO_AVAILABLE_MULTIPLE_OBJ
			"Недоступно під час одночасно обраних декількох процесів."
		}
	},
	{//BY
		{
			//MSG_START_ROBOT_PRESS_MAIN_END
			"Для пачатку работы, нацiснiце клавiшу {38a584}Y"
		},
		{
			//MSG_ANIM_APPLIED_TO_CHARACTER
			"Анiмацыя, ужытая да персанажа"
		},
		{
			//MSG_ANIM_REMOVED_SUCCESS
			"Анiмацыя была паспяхова удалена"
		},
		{
			//MSG_ANIM_EXISTS_WITH_INDEX
			"Анiмацыя з гэтым iндыксам ужо ёсць у праэкце"
		},
		{
			//MSG_PROCESS_START_PRESS_NEW
			"Для пачатка, стварыцце працэс, нацiснiце {38A584}NEW"
		},
		{
			//MSG_START_SELECT_OBJ_PRESS_OBJ
			"Для пачатка, выдзялiце аб’ект, нацiснiце {38A584}Objects"
		},
		{
			//MSG_COLOR_HEX_REMOVED_SUCCESS
			"HEX color code паспяхова знiшчэнны з аб’екта"
		},
		{
			//MSG_INVALID_COLOR_HEX_CODE
			"Няверны HEX color code"
		},
		{
			//MSG_COLOR_HEX_APPLIED_SUCCESS
			"HEX color code паспяхова прымянены да аб’екту"
		},
		{
			//MSG_COLOR_REMOVED_SUCCESS
			"Колер паспяхова знiшчэнны"
		},
		{
			//MSG_COLOR_EXISTS_WITH_HEX_CODE
			"Гэты HEX колер code ужо ёсць у праэкце"
		},
		{
			//MSG_NEW_COLOR_ADDED_TO_LIST
			"Новы колер паспяхова быў створан у спiску"
		},
		{
			//MSG_NO_CREATED_PROCESS_FOUND
			"Створаны працэс адсутнiчае"
		},
		{
			//MSG_MAX_COMMENT_LENGTH_IS_CHARS
			"Максiмальная даўжыня апiсання is 31 сiмвалаў"
		},
		{
			//MSG_OBJECT_DUPLICATED_SUCCESS
			"Аб’ект паспяхова дублiраван"
		},
		{
			//MSG_FREE_LOOK_HOLD_SPRINT_KEY
			"Каб свабодна агледзецца, ўтрымлiвайце нацiснутай клавiшу спрынт({38A584}Shift{FFFFFF}/{38A584}Space{FFFFFF})"
		},
		{
			//MSG_SAVE_PRESS_ICON_CNL_USE_ESC
			"Каб захаваць змены, нацiснiце на {38A584}Значок захавання {FFFFFF}каб адмянiць, нацiснице клавiшу {38A584}ESC"
		},
		{
			//MSG_NOT_SAVED_EDITING_CANCELLED
			"Змены не былi захаваныя, так як рэдагаванне было адменена"
		},
		{
			//MSG_CHANGES_SAVED_AFTER_EDIT
			"Змены пасля рэдагавання былi паспяхова захаваны"
		},
		{
			//MSG_LIST_ATTACHED_OBJECTS_EMPTY
			"Лiст аб’ектаў пусты"
		},
		{
			//MSG_NO_AVAILABLE_ATTACH_SLOTS
			"Няма свабодных слатоў для рэдакцiрвання"
		},
		{
			//MSG_TO_SET_OBJECT_PRESS_OBJECTS
			"Каб усталяваць аб'ект, нацiснiце {38a584}Objects"
		},
		{
			//MSG_TO_MNG_ATTAC_PRESS_MANAGE
			"Каб кiраваць прымацаванымi аб'ектамi, нацiснiце {38a584}Manage"
		},
		{
			//MSG_PRTCT_FRM_ACCIDENTAL_CLICK
			"Абарона ад выпадковых пстрычак"
		},
		{
			//MSG_INVALID_OBJECT_MODEL
			"Няверная мадэль аб’екта"
		},
		{
			//MSG_PRESS_TO_EDIT_START_EDITING
			"Для пачатка рэдакцiравання прыкладанная, нацiснiце клавiшу {38A584}Edit"
		},
		{
			//MSG_OBJECT_REMOVED_SUCCESS
			"Аб’ект паспяхова знiшчан"
		},
		{
			//MSG_OBJECT_MODEL_EXISTS_WITH_ID
			"Аб'ектная мадэль з гэтым iдэнтыфiкатарам ўжо iснуе"
		},
		{
			//MSG_OBJECT_MODEL_ADDED_SUCCESS
			"Мадэль аб’екта была паспяхова створанна у спiсак"
		},
		{
			//MSG_SPECIFY_SKIN_ID_IN_RANGE
			"Укажыце iдэнтыфiкатар скiна ў дыяпазоне ад 1 да 311"
		},
		{
			//MSG_SKIN_SET_SUCCESS
			"Адзенне паспяхова надзето"
		},
		{
			//MSG_CLOSE_CURRENT_PROJECT_FIRST
			"Для пачатка, закройце данны праэкт"
		},
		{
			//MSG_MAX_PROJECT_LENGTH_IS_CHARS
			"Максымальная назва праэкта %d сiмвалоў"
		},
		{
			//MSG_ONLY_LATIN_LETTERS_DIGITS
			"Толькi Лацiнскiя лiтары i чысла без прабелаў разрашаны для ўводу"
		},
		{
			//MSG_PROJECT_WITH_NAME_EXISTS
			"Праэкт з гэтым iмянем ужо ёсц"
		},
		{
			//MSG_PRJCT_NAME_SUCCESS_CREATED
			"Праэкт паспяхова створан"
		},
		{
			//MSG_FREE_LK_MODE_ACTIV_PRS_ESC
			"Каб актываваць рэжым вольнага прагляду, нацiснiце клавiшу {38a584}ESC"
		},
		{
			//MSG_CURSOR_ACTIVATION_PRESS_N
			"Для акцявацыi, нацiснице клавiшу {38A584}N"
		},
		{
			//MSG_PROCESS_SRT_SLCT_OPTION_NEW
			"Для пачатку працэса, выбярыце наладжванне {38A584}NEW"
		},
		{
			//MSG_PROJECTS_LIST_EMPTY
			"Лiст праэктаў пусты"
		},
		{
			//MSG_PRJCT_FILE_NO_FOUND_WH_NAME
			"Файл праекта з названым iмем не знойдзены"
		},
		{
			//MSG_PROJECT_LOADED_SUCCESS
			"Праэкт паспяхова загружан"
		},
		{
			//MSG_PRJCT_RMOVD_FRM_LT_SUCCESS
			"Праэкт паспяхова знiшчэнне з спiску"
		},
		{
			//MSG_NO_ACTIVE_PROJECT_FOUND
			"У вас няма актыўных праэктаў"
		},
		{
			//MSG_CURRENT_PRJCT_CLSD_SUCCESS
			"Данны праэкт паспяхова закрыт"
		},
		{
			//MSG_SMTRY_NOT_FOUND_FREE_SLOT
			"Щоб здійснити симетрію об'єкта, звiльнiть один слот"
		},
		{
			//MSG_DUBLICT_NOT_FOUND_FREE_SLOT
			"Няма вольнага слоту для дубліката, выдаліце адзін існуючы працэс."
		},
		{
			//MSG_CHANGE_BONE
			"Новая косьць паспяхова ўстаноўлена."
		},
		{
			//MSG_MULTIOBJ_INVALID_MODELID
			"У гэтым працэсе не ўстаноўлены аб'ект."
		},
		{
			//MSG_NO_AVAILABLE_MULTIPLE_OBJ
			"Не даступна падчас некалькіх адначасова выбраных працэсаў."
		}
	}
};


